# Clase 10: Vectores, matrices y ecuaciones en NumPy

## Contexto

`Numpy` es la paqueteria de python de calculo científico. Nos provee de herramientas y funciones clave para
para optimizar todos nuestros cálculos. Dentro de los usos más importantes tenemos:

- `Ciencia de datos`: Manipulación eficiente de datasets.
- `Machine Learning`: Cálculo tensorial y operaciones matriciales.
- `Simulaciones`: Cálculos numéricos rápidos y precisos.

El abanico de áreas matemáticas va desde herramientas de álgebra lineal, soluciones de ecuaciones y estadística, así como herramientas avanzadas de análisis funcional como lo es la `transformada de Fourier`.


### Importar paquetería de numpy

In [1]:
import numpy as np  # Mandar a llamar la paqueteria de numpy
print(np.__version__) #version actual

1.26.4


## Creación de vectores y matrices

Numpy nos ofrece herramientas para construir facilmente arreglos que tendrán la función matemática de vectores, matrices o incluso tensores de rango tres o superior.

**NOTAS**
* `np.arange(0, 10, 2)`: es como el `range()` pero de numpy.
* `np.random.rand(3, 3)`: se usa para generar números aleatorios de una distribución uniforme en el intervalo [0, 1).

In [3]:
# Desde listas
arr1 = np.array([1, 2, 3])           # 1D
arr2 = np.array([[1, 2], [3, 4]])    # 2D

# Arrays especiales
zeros = np.zeros((3, 3))             # Matriz de ceros
ones = np.ones((2, 2))               # Matriz de unos
identity = np.eye(3)                 # Matriz identidad
range_arr = np.arange(0, 10, 2)      # Similar a range() pero retorna array
random_arr = np.random.rand(3, 3)    # Valores aleatorios (útil en simulaciones)

#Como se ven estos vectores
print("Vector de tres entradas")
print(arr1)
print("\n Matriz de 2x2")
print(arr2)
print("\n Matriz cero de 3x3")
print(zeros)
print("\n Matriz de 1 de 2x2")
print(ones)
print("\n Matriz identidad de 3x3")
print(identity)
print("\n Vector cuyas entradas toman los valores 0 al 10 en dos en dos")
print(range_arr)
print("\n Vector de tres entradas aleatorias")
print(random_arr)

Vector de tres entradas
[1 2 3]

 Matriz de 2x2
[[1 2]
 [3 4]]

 Matriz cero de 3x3
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 Matriz de 1 de 2x2
[[1. 1.]
 [1. 1.]]

 Matriz identidad de 3x3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 Vector cuyas entradas toman los valores 0 al 10 en dos en dos
[0 2 4 6 8]

 Vector de tres entradas aleatorias
[[0.63277976 0.32233614 0.18666131]
 [0.09616529 0.25373276 0.96012088]
 [0.30429095 0.57261321 0.47866702]]


## Atributos clave


* Las siguientes opciones nos permiten obtener informacion clave de vectores y matrices.

In [4]:
print(arr2.shape)    # Dimensiones (2, 2)
print(arr2.dtype)    # Tipo de datos (int64, float32, etc.)
print(arr2.ndim)     # Número de dimensiones (2)

(2, 2)
int32
2


### Acceder a datos especificos de vectores y matrices

In [7]:
print("TODOS LOS DATOS:\n", arr2)
print("Posicion [1][0]:" , arr2[1, 0])        # 3 (fila 1, columna 0)
print("Todas las filas de la columna 1: ", arr2[:, 1])        # Todas las filas, columna 1 ([2, 4])

TODOS LOS DATOS:
 [[1 2]
 [3 4]]
Posicion [1][0]: 3
Todas las filas de la columna 1:  [2 4]


## Operaciones con vectores y matrices

### Operaciones con vectores
Ahora veremos las operaciones básicas que podemos realizar con vectores, los cuales son

- `Suma de vectores` ($\vec{a}+\vec{b}$)
- `Multiplicación de vectores` ($\alpha\cdot\vec{a}$)
- `Producto interior (punto) entre vectores` ($\vec{a}\cdot\vec{b}$)
- `Producto exterior (cruz) entre vectores` (solo vectores con tres entradas $\vec{a}\times\vec{b}$)

***NOTAS***

Sea el producto cruz entre dos vectores en \(\mathbb{R}^3\):

$$
\vec{a} = \begin{bmatrix} a_1 \\ a_2 \\ a_3 \end{bmatrix}, \quad
\vec{b} = \begin{bmatrix} b_1 \\ b_2 \\ b_3 \end{bmatrix}
$$

El producto cruz (producto vectorial) es:

$$
\vec{a} \times \vec{b} =
\begin{vmatrix}
\hat{i} & \hat{j} & \hat{k} \\
a_1 & a_2 & a_3 \\
b_1 & b_2 & b_3
\end{vmatrix}
=
\hat{i}(a_2 b_3 - a_3 b_2) -
\hat{j}(a_1 b_3 - a_3 b_1) +
\hat{k}(a_1 b_2 - a_2 b_1)
$$


In [11]:
### Vector1 en 3D
a = np.array([1, 2, 3])

### Vector2 en 3D
b = np.array([4, 5, 6])

### Suma de vectores
print(a + b)    # [5, 7, 9] (no requiere bucles)

### Multiplicación vectorial por un escalar.
print(a * 2)    # [2, 4, 6] (broadcasting)

### Producto punto (de vuelve un solo valor)
### 1*4 + 2*5 + 3*6 = 32
producto_punto = np.dot(a, b)
print("FUNCION DOT: ", producto_punto)
print("OPERADOR DOT: ",(a @ b))

### Producto cruz (de vuelve un valor)
producto_cruz = np.cross(a, b)
print(producto_cruz)

[5 7 9]
[2 4 6]
FUNCION DOT:  32
OPERADOR DOT:  32
[-3  6 -3]


### Operaciones con matrices
Ahora veremos las operaciones básicas que podemos realizar con matrices, los cuales son

- Suma de matrices ($A+B$)
- Multiplicación de una matriz por un escalar ($\alpha A$)
- Multiplicación de matrices ($A\cdot B$, la cual se define como $(A\cdot B)_{ij}=\sum_{k=1}^n A_{ik}B_{kj}$)


In [14]:
### Matriz 1 2x2
A = np.array([[1, 2], [3, 4]])

### Matriz 2 2x2
B = np.array([[5, 6], [7, 8]])

### Suma de matricial.
print("Suma A+B:\n",A+B)

### Producto matricial por un escalar
print("A*2:\n",A*2)

### Multiplicación matricial 2x2 * 2x2 --> 2x2
C = np.dot(A, B)
print("\n Producto punto:\n", C)

# Otra forma de calcularla
print("\n A @ B:\n", A @ B)

Suma A+B:
 [[ 6  8]
 [10 12]]
A*2:
 [[2 4]
 [6 8]]

 Producto punto:
 [[19 22]
 [43 50]]

 A @ B:
 [[19 22]
 [43 50]]


### Operaciones avanzadas con matrices
Ahora veremos las operaciones con matrices que nos proporciona el álgebra lineal, algunas de estas con gran utilidad son:

- Determinate de una matriz
- Inversa de una matriz $A A^{-1} = 1$ (`esta solo existe si y solo si` det($A$)=0)
- Obtener valores ($\lambda$) y vectores ($\vec{x}$) propios $A\cdot\vec{x}=\lambda\;\vec{x}$ (`eigenvectors`)

***NOTAS***
* `linalg`:submodulo para la parte de algrebra lineal de numpy.
* Los números de punto flotante (como los `float64` que usa NumPy por defecto) no pueden representar todos los números reales de forma exacta. Muchos números simples como 0.1 o incluso 2.0 tienen representaciones binarias infinitas que se truncan o redondean, introduciendo un pequeño error.

In [16]:
### Calculamos el determinante de A
det = np.linalg.det(A)
print("Determinante:", det)

### Tratar de que vea bonito
print(f"Determinante Format: {det:.2f}")
print("Determinante (redondeado):", round(det, 2))

### Matriz inversa.
inversa = np.linalg.inv(A)
print("\n Matriz inversa:\n", inversa) #calculo de la matriz inversa

### Si multiplicamos A por su inversa, el resultado será 1.
print("\n Comprobación:\n", np.dot(inversa,A)) #comprobemos que es la inversa

### 
print("\n Comprobación (ahora con redondéo de cifras):\n", np.round(np.dot(inversa,A),decimals=5)) #comprobemos que es la inversa

Determinante: -2.0000000000000004
Determinante Format: -2.00
Determinante (redondeado): -2.0

 Matriz inversa:
 [[-2.   1. ]
 [ 1.5 -0.5]]

 Comprobación:
 [[1.0000000e+00 4.4408921e-16]
 [0.0000000e+00 1.0000000e+00]]

 Comprobación (ahora con redondéo de cifras):
 [[1. 0.]
 [0. 1.]]


## Autovectores (Eigenvectors)

* Los autovectores (también llamados vectores propios) son un concepto fundamental en álgebra lineal, especialmente cuando se trabaja con matrices o transformaciones lineales.
* Imagina que la matriz 𝐴 representa una transformación del espacio (como una rotación, estiramiento, compresión, etc.).
* Un autovector es un vector que no cambia de dirección bajo esa transformación. Lo único que cambia es su longitud, y esa longitud cambia en función del autovalor 𝜆.

In [17]:
#ahora calculemos los valores y vectores propios
autovalores, autovectores = np.linalg.eig(A)
print("Autovalores:", autovalores)
print("\n Autovectores:\n", autovectores)

Autovalores: [-0.37228132  5.37228132]

 Autovectores:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
#Comprobemos que esto es cierto
x1=autovectores[:,0]
x2=autovectores[:,1]
mult1=A@x1
teori1=x1*autovalores[0]
print(np.round(mult1-teori1,decimals=5))#Si esto es cero, se cumple de que son valor y vector propio

mult2=A@x2
teori2=x2*autovalores[1]
print(np.round(mult2-teori2,decimals=5))#Si esto es cero, se cumple de que son valor y vector propio



### Calculo de Autovectores

## 📌 Cálculo de autovalores y autovectores

Supongamos que tenemos la siguiente matriz:

$$
A = \begin{bmatrix}
4 & 2 \\
1 & 3
\end{bmatrix}
$$

### 1. Encontrar los autovalores \( \lambda \)

Para encontrar los autovalores, resolvemos la ecuación característica:

$$
\det(A - \lambda I) = 0
$$

Donde \( I \) es la matriz identidad:

$$
A - \lambda I = 
\begin{bmatrix}
4 - \lambda & 2 \\
1 & 3 - \lambda
\end{bmatrix}
$$

Calculamos el determinante:

$$
\begin{aligned}
\det(A - \lambda I) &= (4 - \lambda)(3 - \lambda) - (1)(2) \\
&= (4 - \lambda)(3 - \lambda) - 2 \\
&= 12 - 4\lambda - 3\lambda + \lambda^2 - 2 \\
&= \lambda^2 - 7\lambda + 10
\end{aligned}
$$

Igualamos a cero:

$$
\lambda^2 - 7\lambda + 10 = 0
$$

Resolvemos la ecuación cuadrática:

$$
\lambda = \frac{7 \pm \sqrt{(-7)^2 - 4(1)(10)}}{2(1)} = \frac{7 \pm \sqrt{49 - 40}}{2} = \frac{7 \pm \sqrt{9}}{2}
$$

$$
\lambda_1 = 5, \quad \lambda_2 = 2
$$

---

### 2. Encontrar los autovectores correspondientes

#### 🔹 Para \( \lambda = 5 \):

Resolvemos:

$$
(A - 5I)\vec{v} = 0
$$

$$
A - 5I = \begin{bmatrix}
4 - 5 & 2 \\
1 & 3 - 5
\end{bmatrix}
= \begin{bmatrix}
-1 & 2 \\
1 & -2
\end{bmatrix}
$$

Planteamos el sistema:

$$
\begin{cases}
-1x + 2y = 0 \\
x - 2y = 0
\end{cases}
\quad \Rightarrow \quad x = 2y
$$

Entonces, el autovector es:

$$
\vec{v}_1 = \begin{bmatrix} 2 \\ 1 \end{bmatrix} \quad \text{o cualquier múltiplo}
$$

---

#### 🔹 Para \( \lambda = 2 \):

Resolvemos:

$$
A - 2I = \begin{bmatrix}
4 - 2 & 2 \\
1 & 3 - 2
\end{bmatrix}
= \begin{bmatrix}
2 & 2 \\
1 & 1
\end{bmatrix}
$$

Planteamos el sistema:

$$
\begin{cases}
2x + 2y = 0 \\
x + y = 0
\end{cases}
\quad \Rightarrow \quad x = -y
$$

Entonces, el autovector es:

$$
\vec{v}_2 = \begin{bmatrix} -1 \\ 1 \end{bmatrix} \quad \text{o cualquier múltiplo}
$$

---

### ✅ Resultado final:

- Autovalores: \( \lambda_1 = 5 \), \( \lambda_2 = 2 \)
- Autovectores:
  - Para \( \lambda = 5 \): \( \vec{v}_1 = \begin{bmatrix} 2 \\ 1 \end{bmatrix} \)
  - Para \( \lambda = 2 \): \( \vec{v}_2 = \begin{bmatrix} -1 \\ 1 \end{bmatrix} \)


## Ejemplo práctico
Para ejemplificar el poder de numpy, hagamos un ejemplo prácico que tendrá alta importancia en el futuro. Sumpongamos que tenemos el siguiente sistema de ecuaciones lineales:
<div style="text-align: center;font-size: 20px">
  $2x+y=5$<br>
$x-3y=-1$
</div>
El álgebra lineal nos permite repensar el sistema en forma de matriz,
<div style="text-align: center;font-size: 20px">
$$
\begin{pmatrix}
2 & 1 \\
1 & -3
\end{pmatrix}
    \begin{pmatrix}
    x\\
    y
    \end{pmatrix}=\begin{pmatrix}
    5\\
    -1
    \end{pmatrix}
$$
</div>
Lo primero que haremos es verificar si este sistema tiene solucion. Según los teoremas del álgebra lineal, el sistema tiene solución si y solo si det($M$)$\neq$0, donde $M$ es la matriz del sistema definida como
<div style="text-align: center;font-size: 20px">
$$
M=\begin{pmatrix}
2 & 1 \\
1 & -3
\end{pmatrix}
$$
</div>

In [21]:
### M contedrá los coeficientes de nuestras ignitas
M=np.array([[2,1],[1,-3]])

### Calculamos el determinante de M.
print("det(M): ", np.round(np.linalg.det(M)))

det(M):  -7.0


* `Hemos verificado que el sistema en efecto tiene solución.`
* Ahora podemos proceder a obtener las soluciones con el método que nos apetesca. Para usar las herramientas vistas aqui, obtengamos la solución segun la regla de Cramer:
<div style="text-align: center;font-size: 20px">
$$
\text{si}\; \begin{pmatrix}
a & b \\
c & d
\end{pmatrix}
    \begin{pmatrix}
    x\\
    y
    \end{pmatrix}=\begin{pmatrix}
    f_1\\
    f_2
    \end{pmatrix},
$$
<br>
<br>
</div>
<div style="text-align: center;font-size: 20px">
$$
\text{entonces}\; x= \frac{\text{det}(M_1)}{\text{det}(M)},\;\; y= \frac{\text{det}(M_2)}{\text{det}(M)}
$$
</div>

<div style="text-align: center;font-size: 20px">
$$
\text{en donde se definió}\; M_1=\begin{pmatrix}
f_1 & b \\
f_2 & d
\end{pmatrix},
$$
<br>
</div>
<div style="text-align: center;font-size: 20px">
$$
M_2=\begin{pmatrix}
a & f_1 \\
c & f_2
\end{pmatrix}
$$
</div>


In [19]:
### M1 continee los resultados y la segunda columna de M.
M1=np.array([[5,1],[-1,-3]])

### M2 contiene la primera columna de M y los resultados.
M2=np.array([[2,5],[1,-1]])

### Calculamos los determinantes de cada uno.
det1=np.linalg.det(M1)
det2=np.linalg.det(M2)
detSis=np.linalg.det(M)

print("Las soluciones del sistema son:")
print("\n x = ",np.round(det1/detSis))
print("\n y = ",np.round(det2/detSis))

Las soluciones del sistema son:

 x =  2.0

 y =  1.0


In [22]:
### comprobemos que esto es cierto
sol=np.array([2,1])
print(M@sol)

[ 5 -1]


### El verdadero poder numpy

Lo que hicimos antes fue un ejemplo práctico de como usar las herramientas básicas de numpy para resolver un problema en concreto con el que podríamos encontrarnos en algún análisis. Pero numpy no es numpy solo porque nos permite calcular determinantes fácilmente, sino porque es una paquetería completa que incluye montones de herramientas ya definidas. Por ejemplo, ***INCLUYE UNA FUNCION PARA RESOLVER SISTEMAS DE ECUACIONES***!!!

In [23]:
#La matriz del sistema ya la tenemos definida
print(M)

#Luego definimos el vector de la igualdad
f=np.array([5,-1])

#Ahora llamamos a la instruccion solve
x = np.linalg.solve(M, f)
print("\n Solución:", x)

[[ 2  1]
 [ 1 -3]]

 Solución: [2. 1.]


De una forma similar, podemos encontrar las soluciones de ecuaciones de la forma
<div style="text-align: center;font-size: 20px">
$$
ax^2 + bx + c = 0
$$
</div>

In [24]:
a, b, c = 1, -3, 2  # x² - 3x + 2 = 0
soluciones = np.roots([a, b, c])
print(soluciones)

[2. 1.]


* La instrucción roots tambien funciona para polinomios de orden superior

In [26]:
coeficientes = [1, -6, 11, -6]  # 1x³ - 6x² + 11x - 6
raices = np.roots(coeficientes)
print(raices)

[3. 2. 1.]


In [27]:
#Tambien nos da raíces complejas
print(np.roots([1,0,1])) #x² + 1

[-0.+1.j  0.-1.j]
