# Clase 4: Arreglos en Python y NumPy

## Objetivos de la clase
- Comprender qué son los arreglos y su importancia en Python
- Dominar el uso de listas y sus operaciones principales
- Introducir el uso de NumPy para operaciones numéricas eficientes
- Aplicar los conocimientos con ejercicios prácticos
___

## Arreglos

### 1. Introducción a los arreglos

Los arreglos son estructuras de datos fundamentales que nos permiten almacenar múltiples valores en una sola variable. En Python, existen varios tipos:

- **Listas**: Colecciones ordenadas y mutables
- **Tuplas**: Colecciones ordenadas e inmutables  
- **Arrays del módulo array**: Arrays tipados para eficiencia de memoria
- **NumPy arrays**: Optimizados para computación científica





In [ ]:
# Ejemplo de diferentes tipos de arreglos
print("=== EJEMPLOS DE ARREGLOS ===")

# Lista (puede contener diferentes tipos de datos)
mi_lista = [1, "dos", 3.0, True]
print(f"Lista: {mi_lista}")

# Tupla (inmutable)
mi_tupla = (1, 2, 3, 4)
print(f"Tupla: {mi_tupla}")

# Array del módulo array (tipado)
import array
mi_array = array.array('i', [1, 2, 3, 4])  # 'i' para enteros
print(f"Array: {mi_array}")

# NumPy array (eficiente para cálculos numéricos)
import numpy as np
mi_numpy_array = np.array([1, 2, 3, 4])
print(f"NumPy array: {mi_numpy_array}")

=== EJEMPLOS DE ARREGLOS ===
Lista: [1, 'dos', 3.0, True]
Tupla: (1, 2, 3, 4)
Array: array('i', [1, 2, 3, 4])
NumPy array: [1 2 3 4]


### 2. Listas en Python

Las listas son el tipo de arreglo más versátil en Python. Permiten almacenar diferentes tipos de datos y son mutables (podemos modificar sus elementos).

In [ ]:
# Creación y acceso a listas
print("=== CREACIÓN Y ACCESO A LISTAS ===")

# Crear listas
frutas = ["banana", "manzana", "cereza", "naranja","piña"]
numeros = [1, 2, 3, 4, 5]
mezclada = [10, "texto", 3.14, True]

print(f"Frutas: {frutas}")
print(f"Números: {numeros}")
print(f"Mezclada: {mezclada}")

# Acceder a elementos
print(f"\n=== ACCESO A ELEMENTOS ===")
print(f"Primera fruta: {numeros[0]}")      # Primer elemento (index 0)
print(f"Última fruta: {frutas[-1]}")      # Último elemento
print(f"Tres primeras frutas: {frutas[1:4]}")  # Sublista (slicing)

i=0;
while i<=4:
  print(f"La fruta en la posicion {i} es {frutas[i]}")
  i+=1 #contador de las posiciones de la lista


=== CREACIÓN Y ACCESO A LISTAS ===
Frutas: ['banana', 'manzana', 'cereza', 'naranja', 'piña']
Números: [1, 2, 3, 4, 5]
Mezclada: [10, 'texto', 3.14, True]

=== ACCESO A ELEMENTOS ===
Primera fruta: 1
Última fruta: piña
Tres primeras frutas: ['manzana', 'cereza', 'naranja']
La fruta en la posicion 0 es banana
La fruta en la posicion 1 es manzana
La fruta en la posicion 2 es cereza
La fruta en la posicion 3 es naranja
La fruta en la posicion 4 es piña


### 3. Operaciones con listas

Python ofrece múltiples métodos para manipular listas:

In [ ]:
# Operaciones comunes con listas
print("=== OPERACIONES CON LISTAS ===")

mi_lista = [1, 2, 3]
print(f"Lista original: {mi_lista}")

# Agregar elementos
mi_lista.append(4)           # Agrega al final
mi_lista.insert(1, 1.5)      # Inserta en posición específica
mi_lista.extend([5, 6, 7])   # Agrega múltiples elementos

print(f"Después de agregar: {mi_lista}")

# Eliminar elementos
mi_lista.remove(1.5)         # Elimina por valor
eliminado = mi_lista.pop(2)  # Elimina por índice y devuelve el valor
print(f"Elemento eliminado: {eliminado}")
print(f"Después de eliminar: {mi_lista}")

# Otras operaciones útiles
print(f"Longitud: {len(mi_lista)}")
print(f"¿Está el 5?: {5 in mi_lista}")
print(f"Índice del 4: {mi_lista.index(4)}")
print(f"Conteo del 2: {mi_lista.count(2)}")

# Ordenar
mi_lista.sort()
print(f"Ordenada: {mi_lista}")
mi_lista.reverse()
print(f"Revertida: {mi_lista}")


=== OPERACIONES CON LISTAS ===
Lista original: [1, 2, 3]
Después de agregar: [1, 1.5, 2, 3, 4, 5, 6, 7]
Elemento eliminado: 3
Después de eliminar: [1, 2, 4, 5, 6, 7]
Longitud: 6
¿Está el 5?: True
Índice del 4: 2
Conteo del 2: 1
Ordenada: [1, 2, 4, 5, 6, 7]
Revertida: [7, 6, 5, 4, 2, 1]


### 4. Comprensión de listas

La comprensión de listas es una forma concisa y elegante de crear listas en Python. Nos permite transformar y filtrar elementos fácilmente.

In [ ]:
# Comprensión de listas
print("=== COMPRENSIÓN DE LISTAS ===")

# Crear una lista de cuadrados (forma tradicional)
cuadrados_tradicional = []
for x in range(10):
    cuadrados_tradicional.append(x**2)
print(f"Cuadrados (tradicional): {cuadrados_tradicional}")

# Crear la misma lista con comprensión de listas
cuadrados = [x**2 for x in range(10)]
print(f"Cuadrados (comprensión): {cuadrados}")

# Comprensión con condición
pares = [x for x in range(20) if x % 2 == 0]
print(f"Números pares: {pares}")

# Transformación de elementos
frutas = ["manzana", "banana", "cereza"]
frutas_mayusculas = [fruta.upper() for fruta in frutas]
print(f"Frutas en mayúsculas: {frutas_mayusculas}")


=== COMPRENSIÓN DE LISTAS ===
Cuadrados (tradicional): [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
Cuadrados (comprensión): [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
Números pares: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
Frutas en mayúsculas: ['MANZANA', 'BANANA', 'CEREZA']


## Introducción a NumPy

NumPy es una librería fundamental para computación científica en Python. Proporciona arrays multidimensionales y operaciones matemáticas eficientes.

In [ ]:
# Introducción a NumPy
print("=== INTRODUCCIÓN A NUMPY ===")

import numpy as np

# Creación de arrays
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
ceros = np.zeros((3, 3))      # Matriz 3x3 de ceros
unos = np.ones((2, 4))        # Matriz 2x4 de unos
rango = np.arange(0, 12, 3)   # Valores de 0 a 8 en pasos de 2

print(f"Array 1D: {array_1d}")
print(f"Array 2D:\n{array_2d}")
print(f"Matriz de ceros 3x3:\n{ceros}")
print(f"Matriz de unos 2x4:\n{unos}")
print(f"Array con arange: {rango}")

# Operaciones vectorizadas
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print(f"\n=== OPERACIONES VECTORIZADAS ===")
print(f"a + b = {a + b}")          # Suma elemento por elemento
print(f"a * 2 = {a * 2}")          # Multiplicación por escalar
print(f"a * b = {a * b}")          # Multiplicación elemento por elemento
print(f"a.dot(b) = {a.dot(b)}")    # Producto punto
print(f"np.sqrt(a) = {np.sqrt(a)}")  # Raíz cuadrada de cada elemento

# Indexación y slicing avanzado
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"\nMatriz 3x3:\n{matriz}")
print(f"Primera fila: {matriz[0, :]}")
print(f"Última columna: {matriz[:, -1]}")
print(f"Submatriz 2x2: \n{matriz[0:2, 0:2]}")

=== INTRODUCCIÓN A NUMPY ===
Array 1D: [1 2 3 4 5]
Array 2D:
[[1 2 3]
 [4 5 6]]
Matriz de ceros 3x3:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Matriz de unos 2x4:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array con arange: [0 3 6 9]

=== OPERACIONES VECTORIZADAS ===
a + b = [ 6  8 10 12]
a * 2 = [2 4 6 8]
a * b = [ 5 12 21 32]
a.dot(b) = 70
np.sqrt(a) = [1.         1.41421356 1.73205081 2.        ]

Matriz 3x3:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Primera fila: [1 2 3]
Última columna: [1 4 7]
Submatriz 2x2: 
[[1 2]
 [4 5]]


## Ejercicios de ejemplo

Practiquemos lo aprendido con algunos ejercicios:

In [ ]:

print("=== EJERCICIOS DE EJEMPLO ===")

# Ejercicio 1: Filtrar y transformar
print("Ejercicio 1: Números impares al cuadrado")
numeros = list(range(1, 21))
impares_cuadrados = [x**2 for x in numeros if x % 2 != 0]
print(f"Resultado: {impares_cuadrados}")

# Ejercicio 2: Aplanar matriz
print("\nEjercicio 2: Aplanar matriz")
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
plana = [num for fila in matriz for num in fila]
print(f"Matriz: {matriz}")
print(f"Plana: {plana}")

# Ejercicio 3: Operaciones con NumPy
print("\nEjercicio 3: Operaciones con arrays")
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])
suma = vector_a + vector_b
producto_punto = np.dot(vector_a, vector_b)
print(f"Vector A: {vector_a}")
print(f"Vector B: {vector_b}")
print(f"Suma: {suma}")
print(f"Producto punto: {producto_punto}")

# Ejercicio 4: Crear matriz identidad
print("\nEjercicio 4: Matriz identidad")
identidad = np.eye(4)
print("Matriz identidad 4x4:")
print(identidad)

=== EJERCICIOS DE EJEMPLO ===
Ejercicio 1: Números impares al cuadrado
Resultado: [1, 9, 25, 49, 81, 121, 169, 225, 289, 361]

Ejercicio 2: Aplanar matriz
Matriz: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Plana: [1, 2, 3, 4, 5, 6, 7, 8, 9]

Ejercicio 3: Operaciones con arrays
Vector A: [1 2 3]
Vector B: [4 5 6]
Suma: [5 7 9]
Producto punto: 32

Ejercicio 4: Matriz identidad
Matriz identidad 4x4:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Ejercicios de práctica

In [5]:
# Crea un programa que pida al usuario 5 números,
# los almacene en un arreglo y luego calcule la suma total

### Pedimos todos los numeros
i = 0
lista = []
while i < 5:
    numero = int(input("Ingrese un numero para la lista:"))
    lista.append(numero)
    i+=1

### Sumanos todos los valores
suma = 0
i=0
while i < 5:
    suma+=lista[i]
    i+=1


print("Suma:", suma)

Ingrese un numero para la lista: 1
Ingrese un numero para la lista: 2
Ingrese un numero para la lista: 3
Ingrese un numero para la lista: 4
Ingrese un numero para la lista: 5


Suma: 15


In [1]:
# Programa que pide 7 números y cuenta cuántos son pares e impares

### Pedimos todos los numeros
i = 0
lista = []
while i < 7:
    numero = int(input("Ingrese un numero para la lista:"))
    lista.append(numero)
    i+=1

### Sumanos todos los valores
par = 0
impar = 0
i=0
while i < 7:
    if lista[i]%2 == 0:
        par+=1
    else:
        impar +=1
    i+=1
print(f"Números Pares: {par} Números Impares: {impar}")

Ingrese un numero para la lista: 1
Ingrese un numero para la lista: 2
Ingrese un numero para la lista: 3
Ingrese un numero para la lista: 4
Ingrese un numero para la lista: 5
Ingrese un numero para la lista: 6
Ingrese un numero para la lista: 7


Números Pares: 3 Números Impares: 4
